### ISSUE TITLE
Add OmicsPipelines to the MoTrPAC Data Hub

### ISSUE THREAD

**Issue by mihirsamdarshi** [MoTrPAC/motrpac-frontend#267]

**Comment by mihirsamdarshi** [comment]
I'm not too sure how to approach this Jimmy, I was thinking under the Pipelines section of the [Code Repositories](https://motrpac-data.org/code-repositories) page we add a blurb that says:

```
OmicsPipelines is a suite of applications developed by the MoTrPAC Bioinformatics Center to set up, run, and monitor these pipelines. If you want to try these pipelines out yourself, and have an active AWS or Google Cloud account, check it out [here](https://omicspipelines.org)
```

**Comment by mihirsamdarshi** [comment]
On the [Useful Links](https://motrpac-data.org/external-links) page we add a blurb that says:

```
OmicsPipelines is a suite of applications developed by the MoTrPAC Bioinformatics Center to set up, run, and monitor some of our genomics and proteomics pipelines. If you want to try these pipelines out yourself, and have an active AWS or Google Cloud account, check it out [here](https://omicspipelines.org)

**Comment by jimmyzhen** [comment]
I will add the OmicsPipelines to the **Useful Links** page. Is there a representational image/figure/logo to go with the description provided above?

Instead of inserting a blurb oddly onto the **Code Repositories** page, can you just add a **OmicsPipelines** link in the **Resources** dropdown menu that takes users to the site?

**Comment by mihirsamdarshi** [comment]
I think that the picture you used is a good representation of the application
